### ISSUE TITLE
add validation to typing cards in manually

### ISSUE THREAD

**Issue by squigglybob** [squigglybob/dominion-logger#8]
As the cards are typed in they could be validated.

Or
AFTER adding the kingdom
IF some of the cards are not recognised
THEN display a fail, and which cards were not recognized
(fuzzy match to quickly select the closest matching cards)

## Todo

- [ ] as a name is typed, show the cards that are matching that text with a bit of fuzzy searching in a floating box underneath the input
- [ ] Clicking on a card adds it to the kingdom.
- [ ] clicking an x on the card removes it from the kingdom list.
- [ ] pasting in a comma seperated list, adds each of the cards that are recognized to the kingdom
